bau: update rails / activestorage for  CVE-2026-66066
Force connection_pool to stay on compatible 2.x versions,
as connection_pool 3.0.2 breaks at connection_pool.rb:48 with:

    ArgumentError: wrong number of arguments (given 1, expected 0)